sudo: true
language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl mosquitto ; brew services start mosquitto ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mosquitto -d ; fi 

script:
  - mkdir build.paho ; cd build.paho; cmake -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=TRUE .. ; make ; ctest -VV
addons:
  apt:
    packages:
      - mosquitto
      - doxygen